#include <fstream>
#include <iostream>
#include <cstdlib>

using namespace std;

// reg
//   name 
//   address
//   comment
//   field struct 

// field struct
//   name 
//   bit start
//   size
//   default value
//   access type
//   comment

class regTool
{
    public:
	std::string Name;
	std::string Comment;
        int         Addr;	
};
class regToolField 
{
    public:
	std::string Name;
	int         Start;
	int         Size;
	int         DefaultValue;
        std::string AccessType
	std::string comment; 
};

int main ()
{
    std::ifstream regDefineFile("mine.txt");
    std::ofstream regVerilogFile("reg.v");

    char * buffer;
    long   lineSize;

    //check two files
    if(!regDefineFile.is_open()) 
    {
        cout << "Error opening file reg defination\n"; 
        exit (1);
    }

    if (!regVerilogFile.is_open())
    {
        cout << "Error opening file reg verilog file\n"; 
        exit (1);
    } else {
	// put auto genration info
        regVerilogFile << "This file is autogenerated\n";
        regVerilogFile << "\n";
    }

    while (!regDefineFile.eof())
    {
        //read reg define file and gerated the register head file for verilog
	lineSize = 
	regDefineFile.getline(buffer,100);
	cout << buffer << endl;


    }

    regDefineFile.close();
    regVerilogFile.close();

    return 0;
}

// http://www.cnblogs.com/likebeta/archive/2012/06/16/2551662.html
